# reviewdog.yml

runner:
  misspell:
    cmd: misspell $(git ls-files)
    errorformat:
      - "%f:%l:%c: %m"
  cppcheck:
    cmd: "cppcheck --std=c++11 --enable=all --template='{file}:{line}:{column}: ({severity}) {message} {callstack}' $(git ls-files)"
    errorformat:
      - "%f:%l:%c: %m"
      
